services:
  ui:
    container_name: frontend-app
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - '3000:80' # Expose the UI app on port 3000
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - '4000:3000' # Expose the backend on port 4000
    networks:
      - app-network
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local